sudo: false
language: python
python:
    - "2.7"
before_install:
    - git config --global user.email "OpenStack_TravisCI@f5.com"
    - git config --global user.name "Travis F5 Openstack"
install:
    - pip install -r requirements.unit.test.txt
script:
    - flake8 --exclude=docs .
    - cd docs; make html
