sudo: required
services:
- docker
language: python
python:
- '2.7'
install: true
script:
- ./docs/scripts/docker-docs.sh make -C docs/ html
deploy:
- provider: script
  skip_cleanup: true
  on:
    branch: v10.0
    repo: F5Networks/f5-openstack-heat
  script:
  - ./docs/scripts/deploy-docs.sh publish-product-docs-to-prod templates/openstack-heat/newton v10.0
