heat_template_version: 2014-10-16

description: This template deploys standard TMOS data security group.

resources:

   bigip_control_security_group:
    type: OS::Neutron::SecurityGroup
    deletion_policy: Retain
    properties:
      description: security group rules for ha and mirroring self ip address
      name: bigip_control_security_group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
          port_range_min: 1026
          port_range_max: 1043
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 4353
          port_range_max: 4353


